Repository Redaloukil/quizz-your-future, pull requests merged in 2022-03, with the labels that each got.

#23 Made shuffle method and called it in welcome page
  src/data.js
  src/pages/welcomePage.js
Labels: merge-first

#22 QnA Page Issue
  src/pages/questionPage.js
  src/views/lastView.js
Labels: enhancement

#26 Score Keeper
  src/components/navbar.js
  src/components/scoreKeeper.js
  src/constants.js
  src/pages/lastPage.js
  src/pages/questionPage.js
  src/views/lastView.js
Labels: good first issue

#18 added setTimeout to the auto-switcher
  public/style.css
  src/app.js
  src/components/navbar.js
  src/components/scoreKeeper.js
  src/constants.js
  src/data.js
  src/pages/lastPage.js
  src/pages/questionPage.js
  src/views/answerView.js
  src/views/lastView.js
  src/views/questionView.js
  src/views/welcomeView.js
Labels: bug
